language: android
android:
  components:
    - build-tools-22.0.1

notifications:
  email: reyes@digitalruiz.com

before_install:

  # for gradle output style
  - export TERM=dumb

  # environment info
  - ./gradlew -v
  - uname -a

# Let's try to build...
script: ./gradlew clean build
